version: '3.8'
    
services:
  app:
    image: node1/app:1.0
    build: ./app
    container_name: 'node1_app'
    ports:
      - '4200:4200'
    stdin_open: true
    tty: true
    working_dir: '/project'
    volumes:
      - ../app:/project